[package]
name = "lib-q-hash"
version = "0.0.1"
edition = "2021"
authors = ["lib-Q Contributors"]
description = "Post-quantum Hash Functions for lib-Q"
license = "Apache-2.0"
repository = "https://github.com/Enkom-Tech/libQ"
keywords = ["cryptography", "post-quantum", "hash", "shake"]
categories = ["cryptography"]
readme = "README.md"

[dependencies]
lib-q-core = { path = "../lib-q-core" }
zeroize = "1.8.1"
getrandom = { version = "0.3.3", features = ["std"] }
digest = "0.11.0-rc.0"
keccak = { path = "../lib-q-sponge/keccak" }

[dev-dependencies]
digest = { version = "0.11.0-rc.0", features = ["dev"] }
hex-literal = "1"
base16ct = { version = "0.2", features = ["alloc"] }

[features]
default = ["alloc", "oid"]
alloc = ["digest/alloc"]
oid = ["digest/oid"]
zeroize = ["digest/zeroize"]
asm = ["keccak/asm"] # ARMv8 only

[lib]
name = "lib_q_hash"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
