[package]
name = "lib-q-hash"
version = "0.0.1"
edition = "2021"
authors = ["Nexlab-One", "Enkom Tech"]
description = "Post-quantum Hash Functions for lib-Q"
license = "Apache-2.0"
repository = "https://github.com/Enkom-Tech/libQ"
keywords = ["cryptography", "post-quantum", "hash", "shake"]
categories = ["cryptography"]
readme = "README.md"

[dependencies]
lib-q-core = { version = "0.0.1", path = "../lib-q-core" }
zeroize = "1.8.1"
getrandom = { version = "0.3.3", features = ["std"] }
digest = "0.11.0-rc.0"
lib-q-keccak = { version = "0.0.1", path = "../lib-q-keccak" }
lib-q-k12 = { version = "0.0.1", path = "../lib-q-k12" }
lib-q-sha3 = { version = "0.0.1", path = "../lib-q-sha3" }
rayon = { version = "1.11.0", optional = true }

[dev-dependencies]
digest = { version = "0.11.0-rc.0", features = ["dev"] }
hex-literal = "1"
base16ct = { version = "0.2.0", features = ["alloc"] }

[features]
default = ["alloc", "oid"]
alloc = ["digest/alloc"]
oid = ["digest/oid"]
zeroize = ["digest/zeroize"]
asm = ["lib-q-keccak/asm"] # ARMv8 only
simd = ["lib-q-keccak/simd"] # Enable SIMD optimizations
nightly = ["lib-q-keccak/nightly"] # Enable nightly Rust features
advanced-simd = ["lib-q-keccak/advanced-simd"] # Enable advanced SIMD features
multithreading = ["lib-q-keccak/multithreading"] # Enable multi-threading support
parallelhash = ["rayon"] # Enable parallel processing for ParallelHash

[lib]
name = "lib_q_hash"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
