[package]
name = "ascon"
version = "0.5.0-pre"
description = "Pure Rust implementation of the Ascon permutation"
authors = [
    "Sebastian Ramacher <sebastian.ramacher@ait.ac.at>",
    "RustCrypto Developers",
    "Nexlab-One",
    "Enkom Tech"
]
license = "Apache-2.0"
documentation = "https://docs.rs/ascon"
homepage = "https://github.com/lib-q/lib-q-sponge/tree/master/ascon"
repository = "https://github.com/lib-q/lib-q-sponge"
keywords = ["Ascon", "crypto", "permutation"]
categories = ["cryptography", "no-std"]
readme = "README.md"
edition = "2021"
rust-version = "1.81"

[dependencies]
zeroize = { version = "1.8.1", default-features = false, optional=true }

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }
rand = "0.9.2"

[features]
no_unroll = [] # Do not unroll loops for binary size reduction
nightly = [] # Enable nightly-only features like benchmarking

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "ascon"
harness = false
