[package]
name = "lib-q-keccak"
version.workspace = true
description = """
Pure Rust implementation of the Keccak sponge function including the keccak-f
and keccak-p variants for lib-Q
"""
authors.workspace = true
license.workspace = true
documentation = "https://docs.rs/lib-q-keccak"
homepage = "https://github.com/Enkom-Tech/libQ/tree/main/lib-q-sponge/keccak"
repository.workspace = true
keywords = ["crypto", "sponge", "keccak", "keccak-f", "keccak-p", "lib-q"]
categories = ["cryptography", "no-std"]
readme.workspace = true
edition.workspace = true
rust-version = "1.89"

[features]
asm = []       # Use optimized assembly when available (ARMv8, x86_64 AVX2/AVX-512)
no_unroll = [] # Do no unroll loops for binary size reduction
simd = []      # Use core::simd (nightly-only)
nightly = []   # Enable nightly-only features like benchmarking
advanced-simd = ["simd"]  # Enable advanced SIMD features (requires nightly)
std = []       # Enable std support (required for multi-threading)
multithreading = ["std"]  # Enable multi-threading support (requires std)

[target.'cfg(target_arch = "aarch64")'.dependencies]
cpufeatures = "0.2.17"

[dependencies]
num_cpus = "1.17.0"

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.30.1"

[lib]
name = "lib_q_keccak"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(hax)',
    'cfg(eurydice)',
    'cfg(doc_cfg)',
    'cfg(simd128)',
    'cfg(simd256)',
    'cfg(aarch64)',
    'cfg(x86_64)',
] }