//! Byte-exact conformance against the **official upstream HQC reference implementation**.
//!
//! Oracle: `intermediates_values` as published by the HQC team at
//! <https://gitlab.com/pqc-hqc/hqc> at release tag **v5.0.0** (commit `f46e542`, 2025-08-22 — the
//! revision matching the published `hqc_specifications_2025_08_22.pdf`). The files under
//! `kats/reference-intermediates/hqc-{1,3,5}/intermediates_values` are **verbatim copies of that
//! upstream artifact** — they are NOT generated by this crate. See
//! `kats/reference-intermediates/PROVENANCE.md` for sha256 sums and the exact build recipe used to
//! reproduce them from upstream C source.
//!
//! What the oracle fixes. The upstream `tests/kats/test_intermediates_values.c` harness runs
//! `prng_init(entropy = [0,1,..,47], NULL, 48, 0)` once, then a single KEM keygen/encaps/decaps.
//! The reference PRNG is SHAKE256 (`src/common/symmetric.c`), so its stream is
//! `SHAKE256(entropy || 0x00)`; keygen consumes bytes `[0..32)` as `seed_kem`, encaps consumes the
//! next `PARAM_SECURITY_BYTES` as `m` and then 16 bytes as `salt`. Every derived value is printed,
//! so the whole derivation chain is externally pinned, seed to shared secret.
//!
//! What this test proves: given the reference's `seed_kem` (and, for HQC-128, its `m` and `salt`),
//! this crate reproduces upstream's `seed_dk`, `sigma`, public key, ciphertext and shared secret
//! **byte for byte**.
//!
//! One documented gap, deliberately not papered over:
//!
//! 1. The `PQCkemKAT_*.rsp` KEM-boundary vectors are NOT covered. Those reseed the PRNG from each
//!    row's 48-byte `seed` and then *draw* `seed_kem` from it
//!    (`seed_kem = SHAKE256(seed48 || 0x00)[0..32]`, `src/common/kem.c`), whereas
//!    `HqcKem::keygen_with_seed` uses `seed[0..32]` directly.
//!
//! Previously there was a second gap: encaps/decaps was compared for HQC-128 only, because this
//! crate hardwired `m` and `sigma` to 16 bytes while upstream sizes both at `PARAM_SECURITY_BYTES`
//! = 16/24/32, so the HQC-192/256 reference values could not even be supplied to the API. That is
//! fixed (card `t_d2ee7042`) and all three levels are now compared through the full chain.
//!
//! See `kats/README.md`.

#![cfg(all(feature = "alloc", feature = "hqc", feature = "random"))]

use std::fs;
use std::path::Path;

use lib_q_hqc::hqc_kem::HqcKem;
use lib_q_hqc::internal::shake256::Shake256Xof;
use lib_q_hqc::params::{
    Hqc1Params,
    Hqc3Params,
    Hqc5Params,
    HqcParams,
};

/// Reference `SEED_BYTES`.
const SEED_BYTES: usize = 32;
/// Reference `SALT_BYTES`.
const SALT_BYTES: usize = 16;

/// Pull the first `^<key>: <hex>` line out of the upstream intermediates dump.
fn field(text: &str, key: &str) -> Vec<u8> {
    let prefix = format!("{key}: ");
    let line = text
        .lines()
        .map(str::trim_start)
        .find(|l| l.starts_with(&prefix))
        .unwrap_or_else(|| panic!("field `{key}` not found in reference intermediates file"));
    let hex_str = line[prefix.len()..].trim();
    hex::decode(hex_str).unwrap_or_else(|e| panic!("field `{key}` is not hex: {e}"))
}

fn fixture(variant: &str) -> String {
    let path = Path::new("kats/reference-intermediates")
        .join(variant)
        .join("intermediates_values");
    fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read oracle {}: {e}", path.display()))
}

/// `prng_init([0..47], NULL, 48, 0)` then `prng_get_bytes` — reference `src/common/symmetric.c`.
fn reference_prng_stream(out: &mut [u8]) {
    let mut entropy = [0u8; 48];
    for (i, b) in entropy.iter_mut().enumerate() {
        *b = i as u8;
    }
    let mut prng = Shake256Xof::new();
    prng.init_with_domain(&entropy, 0)
        .expect("shake256 init failed");
    prng.squeeze(out).expect("shake256 squeeze failed");
}

/// Keygen conformance: externally pinned at every parameter set.
fn check_keygen<P: HqcParams>(variant: &str) {
    let text = fixture(variant);

    let seed_kem = field(&text, "seed_kem");
    let seed_dk = field(&text, "seed_dk");
    let sigma = field(&text, "sigma");
    let ek_kem = field(&text, "ek_kem");
    let m = field(&text, "m");
    let salt = field(&text, "salt");

    assert_eq!(
        seed_kem.len(),
        SEED_BYTES,
        "{variant}: oracle seed_kem size"
    );
    assert_eq!(salt.len(), SALT_BYTES, "{variant}: oracle salt size");
    assert_eq!(
        sigma.len(),
        P::K,
        "{variant}: oracle sigma size should be PARAM_SECURITY_BYTES"
    );
    assert_eq!(m.len(), P::K, "{variant}: oracle m size");
    assert_eq!(
        ek_kem.len(),
        P::PUBLIC_KEY_BYTES,
        "{variant}: oracle ek_kem size vs PUBLIC_KEY_BYTES"
    );

    // (a) The oracle's own seed_kem/m/salt come from the reference SHAKE256 PRNG. Recomputing them
    // here anchors this crate's SHAKE256 against upstream before any HQC-specific code runs.
    let mut stream = vec![0u8; SEED_BYTES + m.len() + SALT_BYTES];
    reference_prng_stream(&mut stream);
    assert_eq!(
        &stream[..SEED_BYTES],
        &seed_kem[..],
        "{variant}: SHAKE256([0..47]||0x00)[0..32] != reference seed_kem"
    );
    assert_eq!(
        &stream[SEED_BYTES..SEED_BYTES + m.len()],
        &m[..],
        "{variant}: PRNG stream after seed_kem != reference m"
    );
    assert_eq!(
        &stream[SEED_BYTES + m.len()..],
        &salt[..],
        "{variant}: PRNG stream after m != reference salt"
    );

    // (b)-(f) Keygen. `keygen_with_seed` takes the reference `seed_kem` in its first 32 bytes.
    let kem = HqcKem::<P>::new().expect("HqcKem::new");
    let mut seed48 = [0u8; 48];
    seed48[..SEED_BYTES].copy_from_slice(&seed_kem);
    let (pk, sk) = kem.keygen_with_seed(&seed48).expect("keygen_with_seed");

    // Reference `dk_pke` is `seed_dk` (`hqc.c`: `memcpy(dk_pke, seed_dk, SEED_BYTES)`).
    let sk_bytes = sk.as_bytes();
    let dk_pke = &sk_bytes[P::PUBLIC_KEY_BYTES..P::PUBLIC_KEY_BYTES + SEED_BYTES];
    assert_eq!(
        dk_pke,
        &seed_dk[..],
        "{variant}: derived dk_pke (= seed_dk) != reference"
    );
    assert_eq!(
        pk.as_bytes(),
        &ek_kem[..],
        "{variant}: public key != reference ek_kem"
    );

    // `sigma` is `PARAM_SECURITY_BYTES` = `P::K` wide at every level, and comparable at every
    // level since the fix for card `t_d2ee7042`.
    let sigma_actual =
        &sk_bytes[P::PUBLIC_KEY_BYTES + SEED_BYTES..P::PUBLIC_KEY_BYTES + SEED_BYTES + P::K];
    assert_eq!(
        sigma_actual,
        &sigma[..],
        "{variant}: derived sigma != reference"
    );
}

/// Full KEM conformance at one parameter set: ciphertext and shared secret byte-exact vs upstream.
fn check_encaps_decaps<P: HqcParams>(variant: &str) {
    let text = fixture(variant);
    let seed_kem = field(&text, "seed_kem");
    let m = field(&text, "m");
    let salt = field(&text, "salt");
    let c_kem = field(&text, "c_kem");
    let k = field(&text, "K");

    assert_eq!(
        m.len(),
        P::K,
        "{variant}: oracle m size should be PARAM_SECURITY_BYTES"
    );

    let kem = HqcKem::<P>::new().expect("HqcKem::new");
    let mut seed48 = [0u8; 48];
    seed48[..SEED_BYTES].copy_from_slice(&seed_kem);
    let (pk, sk) = kem.keygen_with_seed(&seed48).expect("keygen_with_seed");

    let mut salt_arr = [0u8; SALT_BYTES];
    salt_arr.copy_from_slice(&salt);

    let (ct, ss) = kem
        .encapsulate_with_m_salt(&pk, &m, &salt_arr)
        .expect("encapsulate_with_m_salt");
    assert_eq!(
        ct.as_bytes().len(),
        c_kem.len(),
        "{variant}: ciphertext length vs reference c_kem"
    );
    assert_eq!(
        ct.as_bytes(),
        c_kem,
        "{variant}: ciphertext != reference c_kem"
    );
    assert_eq!(
        ss.as_bytes(),
        &k[..],
        "{variant}: shared secret != reference K"
    );

    let ss2 = kem.decapsulate(&sk, &ct).expect("decapsulate");
    assert_eq!(
        ss2.as_bytes(),
        &k[..],
        "{variant}: decapsulated shared secret != reference K"
    );
}

#[test]
fn hqc_128_keygen_matches_reference_intermediates() {
    check_keygen::<Hqc1Params>("hqc-1");
}

/// HQC-192 keygen conformance against upstream HQC v5.0.0
/// (`src/ref/hqc-3/parameters.h`: `PARAM_OMEGA` = 100, `PARAM_OMEGA_R` = 114).
/// Previously RED because `Hqc3Params::OMEGA`/`OMEGA_R` carried stale 103/115 values; corrected,
/// see `omega_matches_reference_v5_0_0` below for the drift guard.
#[test]
fn hqc_192_keygen_matches_reference_intermediates() {
    check_keygen::<Hqc3Params>("hqc-3");
}

/// HQC-256 keygen conformance against upstream HQC v5.0.0
/// (`src/ref/hqc-5/parameters.h`: `PARAM_OMEGA` = 131, `PARAM_OMEGA_R` = 149).
/// Previously RED because `Hqc5Params::OMEGA` carried a stale 134 value; corrected, see
/// `omega_matches_reference_v5_0_0` below for the drift guard.
#[test]
fn hqc_256_keygen_matches_reference_intermediates() {
    check_keygen::<Hqc5Params>("hqc-5");
}

/// Pin `OMEGA`/`OMEGA_R` to the upstream HQC v5.0.0 values so they cannot silently drift again.
///
/// Renamed from `omega_deviation_from_reference_is_pinned` (which pinned the *wrong*, deviating
/// 103/115/134 values found before this crate was moved onto v5.0.0). This test now asserts the
/// *correct* upstream constants; if either constant changes for any variant, this test — and the
/// two keygen conformance tests above — will go red.
///
/// Upstream v5.0.0 `src/ref/hqc-{1,3,5}/parameters.h`:
/// `PARAM_OMEGA` = 66 / 100 / 131, `PARAM_OMEGA_R` = 75 / 114 / 149.
#[test]
fn omega_matches_reference_v5_0_0() {
    assert_eq!(Hqc1Params::OMEGA, 66, "HQC-128 OMEGA (upstream: 66)");
    assert_eq!(Hqc1Params::OMEGA_R, 75, "HQC-128 OMEGA_R (upstream: 75)");

    assert_eq!(Hqc3Params::OMEGA, 100, "HQC-192 OMEGA (upstream: 100)");
    assert_eq!(Hqc3Params::OMEGA_R, 114, "HQC-192 OMEGA_R (upstream: 114)");

    assert_eq!(Hqc5Params::OMEGA, 131, "HQC-256 OMEGA (upstream: 131)");
    assert_eq!(Hqc5Params::OMEGA_R, 149, "HQC-256 OMEGA_R (upstream: 149)");
}

/// Full KEM conformance for HQC-128: ciphertext and shared secret byte-exact vs upstream.
#[test]
fn hqc_128_encaps_decaps_matches_reference_intermediates() {
    check_encaps_decaps::<Hqc1Params>("hqc-1");
}

/// Full KEM conformance for HQC-192 (`PARAM_SECURITY_BYTES` = 24). Previously impossible to run:
/// the API could not accept a 24-byte `m`. Card `t_d2ee7042`.
#[test]
fn hqc_192_encaps_decaps_matches_reference_intermediates() {
    check_encaps_decaps::<Hqc3Params>("hqc-3");
}

/// Full KEM conformance for HQC-256 (`PARAM_SECURITY_BYTES` = 32). Card `t_d2ee7042`.
#[test]
fn hqc_256_encaps_decaps_matches_reference_intermediates() {
    check_encaps_decaps::<Hqc5Params>("hqc-5");
}

/// The defect this fixes was an *entropy* one, not only a conformance one: the shared secret is
/// `G(H(ek) ‖ m ‖ salt)`, and of those three inputs `H(ek)` is public and `salt` is transmitted in
/// the clear, so `m` is the only secret and `H(shared secret) <= |m|`. A hardwired 16-byte `m`
/// therefore capped HQC-192 and HQC-256 shared secrets at 128 bits regardless of the parameter
/// set. Pin the sampled width so that cannot silently regress.
#[test]
fn secret_input_m_is_full_width_at_every_level() {
    assert_eq!(Hqc1Params::K, 16, "HQC-128 PARAM_SECURITY_BYTES");
    assert_eq!(Hqc3Params::K, 24, "HQC-192 PARAM_SECURITY_BYTES");
    assert_eq!(Hqc5Params::K, 32, "HQC-256 PARAM_SECURITY_BYTES");

    // A 16-byte `m` must now be rejected outright at the higher levels rather than silently
    // accepted as a short secret.
    let kem = HqcKem::<Hqc5Params>::new().expect("HqcKem::new");
    let (pk, _sk) = kem.keygen_with_seed(&[0x2Au8; 48]).expect("keygen");
    assert!(
        kem.encapsulate_with_m_salt(&pk, &[0u8; 16], &[0u8; SALT_BYTES])
            .is_err(),
        "HQC-256 must reject a 16-byte m"
    );
}
