[package]
name = "lib-q-ml-kem"
description = """
Pure Rust implementation of the Module-Lattice-Based Key-Encapsulation Mechanism Standard
(formerly known as Kyber) as described in FIPS 203
"""
version = "0.0.1"
edition = "2024"
rust-version = "1.89"
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/Enkom-Tech/libQ"
repository = "https://github.com/Enkom-Tech/libQ"
documentation = "https://docs.rs/lib-q-ml-kem"
categories = ["cryptography", "no-std", "wasm"]
keywords = ["crypto", "ml-kem", "lattice", "post-quantum", "nist"]
exclude = ["tests/key-gen.rs", "tests/key-gen.json", "tests/encap-decap.rs", "tests/encap-decap.json"]

[features]
default = []
deterministic = [] # Expose deterministic generation and encapsulation functions
zeroize = ["dep:zeroize"]
wasm = ["wasm-bindgen", "js-sys"]

[dependencies]
hybrid-array = { version = "0.3.1", features = ["extra-sizes"] }
rand_core = "0.9.3"
lib-q-sha3 = { path = "../lib-q-sha3" }
zeroize = { version = "1.8.1", optional = true, default-features = false }

# WASM bindings
wasm-bindgen = { version = "0.2.100", optional = true, features = ["serde-serialize"] }
js-sys = { version = "0.3.77", optional = true }

[dev-dependencies]
criterion = "0.7.0"
hex = { version = "0.4.3", features = ["serde"] }
hex-literal = "1.0.0"
num-rational = { version = "0.4.2", default-features = false, features = ["num-bigint"] }
rand = "0.9.2"
crypto-common = { version = "0.2.0-rc.3", features = ["rand_core"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"

[[bench]]
name = "mlkem"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
