[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[target.wasm32-unknown-emscripten]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[env]
CARGO_CFG_GETRANDOM_BACKEND = "wasm_js"
