name: Test K12
description: Run K12 (KangarooTwelve) tests with security validation and comprehensive feature testing
inputs:
  working-directory:
    description: Working directory for K12 testing
    default: lib-q-hash
    required: true
  features:
    description: Features to enable for testing
    default: "alloc,oid"
    required: false
  rust-version:
    description: Rust toolchain version to use
    default: "stable"
    required: false
  run-benchmarks:
    description: Whether to run benchmarks (requires nightly)
    default: "false"
    required: false
  test-algorithms:
    description: Specific algorithms to test
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-version }}
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-k12-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-k12-
    
    - name: Security audit
      shell: bash
      run: |
        echo "Running security audit for K12..."
        cargo install cargo-audit --locked
        cargo audit --deny warnings
        echo "Security audit completed successfully"
    
    - name: Check formatting
      shell: bash
      run: |
        echo "Checking code formatting..."
        cd ${{ inputs.working-directory }}
        cargo fmt --all -- --check
        echo "Formatting check completed"
    
    - name: Clippy linting
      shell: bash
      run: |
        echo "Running Clippy linting..."
        cd ${{ inputs.working-directory }}
        cargo clippy --all-targets --all-features -- -D warnings
        echo "Clippy linting completed"
    
    - name: Build with default features
      shell: bash
      run: |
        echo "Building with default features..."
        cd ${{ inputs.working-directory }}
        cargo build --features "${{ inputs.features }}"
        echo "Build completed"
    
    - name: Build with all features
      shell: bash
      run: |
        echo "Building with all features..."
        cd ${{ inputs.working-directory }}
        cargo build --all-features
        echo "Build with all features completed"
    
    - name: Run all tests
      shell: bash
      run: |
        echo "Running all tests..."
        cd ${{ inputs.working-directory }}
        cargo test --features "${{ inputs.features }}"
        echo "All tests completed"
    
    - name: Test K12 implementations
      shell: bash
      run: |
        echo "Testing K12 implementations..."
        cd ${{ inputs.working-directory }}
        cargo test test_k12_implementations --features "${{ inputs.features }}"
        echo "K12 implementation tests completed"
    
    - name: Test K12 with customization
      shell: bash
      run: |
        echo "Testing K12 with customization..."
        cd ${{ inputs.working-directory }}
        cargo test test_k12_implementations --features "${{ inputs.features }}" -- --nocapture
        echo "K12 customization tests completed"
    
    - name: Test K12 hash creation
      shell: bash
      run: |
        echo "Testing K12 hash creation..."
        cd ${{ inputs.working-directory }}
        cargo test test_create_hash_by_name --features "${{ inputs.features }}" -- --nocapture | grep -i k12 || true
        echo "K12 hash creation tests completed"
    
    - name: Test K12 length encoding
      shell: bash
      run: |
        echo "Testing K12 length encoding..."
        cd ${{ inputs.working-directory }}
        cargo test test_length_encode --features "${{ inputs.features }}"
        echo "K12 length encoding tests completed"
    
    - name: Cross-compilation test (ARM64)
      shell: bash
      run: |
        echo "Testing ARM64 cross-compilation..."
        cd ${{ inputs.working-directory }}
        rustup target add aarch64-unknown-linux-gnu
        cargo check --target aarch64-unknown-linux-gnu --features "${{ inputs.features }}"
        echo "Cross-compilation test completed"
    
    - name: WASM compilation test
      shell: bash
      run: |
        echo "Testing WASM compilation..."
        cd ${{ inputs.working-directory }}
        rustup target add wasm32-unknown-unknown
        cargo check --target wasm32-unknown-unknown --features "${{ inputs.features }}"
        echo "WASM compilation test completed"
    
    - name: Feature powerset test
      shell: bash
      run: |
        echo "Testing feature combinations..."
        cd ${{ inputs.working-directory }}
        cargo install cargo-hack
        cargo hack test --feature-powerset --exclude-features default
        echo "Feature powerset test completed"
    
    - name: Run benchmarks (nightly only)
      if: inputs.run-benchmarks == 'true' && inputs.rust-version == 'nightly'
      shell: bash
      run: |
        echo "Running K12 benchmarks..."
        cd ${{ inputs.working-directory }}
        cargo bench --features "nightly" --bench k12 || echo "No K12 benchmarks found"
        echo "K12 benchmarks completed"
    
    - name: Test K12 integration
      shell: bash
      run: |
        echo "Testing K12 integration..."
        cd ${{ inputs.working-directory }}
        # Test that K12 is properly integrated with the main hash system
        cargo test --features "${{ inputs.features }}" -- --nocapture | grep -i "kangaroo\|k12" || true
        echo "K12 integration tests completed"
