//! Known-answer tests against the canonical vectors generated by the Zig
//! research harness. Passing these proves Rust and Zig agree on the frozen-draft
//! profile across the full boundary matrix (cross-validation, PLAN Part 6).

use lib_q_sah::{Sah256, Sah256Key, Sah256Nonce};

fn unhex(s: &str) -> Vec<u8> {
    assert!(s.len().is_multiple_of(2), "odd-length hex");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
        .collect()
}

#[test]
fn kat_sah256_v0_3_0() {
    let raw = include_str!("vectors/kat_sah256_v0.3.0.json");
    let doc: serde_json::Value = serde_json::from_str(raw).expect("parse KAT json");
    let cases = doc["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty(), "no KAT cases");

    let mut checked = 0usize;
    for case in cases {
        let tc = case["tc"].as_u64().unwrap();
        let key = Sah256Key::from_slice(&unhex(case["key"].as_str().unwrap())).unwrap();
        let nonce = Sah256Nonce::from_slice(&unhex(case["nonce"].as_str().unwrap())).unwrap();
        let aad = unhex(case["aad"].as_str().unwrap());
        let pt = unhex(case["pt"].as_str().unwrap());
        let expect_ct = unhex(case["ct"].as_str().unwrap());
        let expect_tag = unhex(case["tag"].as_str().unwrap());

        // Encrypt and match ct + tag exactly.
        let mut ct = vec![0u8; pt.len()];
        let tag = Sah256::seal_detached(&key, &nonce, &aad, &pt, &mut ct).unwrap();
        assert_eq!(ct, expect_ct, "tc {tc}: ciphertext mismatch");
        assert_eq!(tag.as_slice(), expect_tag.as_slice(), "tc {tc}: tag mismatch");

        // Decrypt and recover the plaintext.
        let tag_arr: [u8; 16] = expect_tag.clone().try_into().unwrap();
        let mut rt = vec![0u8; expect_ct.len()];
        Sah256::open_detached(&key, &nonce, &aad, &expect_ct, &tag_arr, &mut rt)
            .unwrap_or_else(|_| panic!("tc {tc}: open failed"));
        assert_eq!(rt, pt, "tc {tc}: decrypted plaintext mismatch");

        checked += 1;
    }
    assert_eq!(checked, cases.len());
}
