#!/usr/bin/env python3
"""Self-test for `ci_guard_kat_provenance.py`: prove each CHECK can actually FAIL.

Why this exists
---------------
The provenance guard is the systemic half of card t_71d4f79a: it is what stops a self-generated
vector file from being named or placed as if it were genuine upstream reference data. A guard in
that role is only worth what its failure modes are worth, and a guard that returns clean on every
possible input looks maximally rigorous while proving nothing. That is the exact class of defect
the card was filed about, so leaving the guard itself unpinned would repeat it one level up.

The guard's checks were verified by hand to fail correctly when this was written. Hand
verification does not survive the session, and a later refactor can silently invert a verdict
(that has happened in this repo before, to the cfg-feature guard). This file turns that one-off
into something CI re-proves on every run.

How it works
------------
`ci_guard_kat_provenance.py` already takes the repo root as argv[1], so no refactor is needed: we
build a small synthetic repo in a temp dir, run the real guard against it as a subprocess, and
assert on its exit code and output. Each case mutates ONE thing away from a known-good fixture,
so a case that fails for an unrelated reason is visible rather than being read as a pass.

The baseline case matters as much as the mutations: if the fixture did not pass cleanly, every
"mutation caused a failure" result below would be vacuous, because the failure could predate the
mutation.

Run: python scripts/selftest_kat_provenance_guard.py
"""

from __future__ import annotations

import hashlib
import pathlib
import shutil
import subprocess
import sys
import tempfile

GUARD = pathlib.Path(__file__).resolve().parent / "ci_guard_kat_provenance.py"

VECTOR_BODY = "count = 0\nseed = 00112233\nss = AABBCCDD\n"


def sha256_of(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def build_fixture(tmp: pathlib.Path) -> None:
    """A minimal repo that the guard should accept, with one self-generated vector."""
    vectors = tmp / "vectors"
    vectors.mkdir(parents=True, exist_ok=True)

    content = "# self-generated by the provenance guard self-test fixture\n" + VECTOR_BODY
    (vectors / "fixture_regression_pin.rsp").write_text(content, encoding="utf-8")

    manifest = f"""
[scan]
roots = ["vectors"]
extensions = ["rsp"]

[[kat]]
path = "vectors/fixture_regression_pin.rsp"
origin = "self-generated"
generator = "provenance guard self-test fixture"
sha256 = "{sha256_of(content)}"
""".lstrip()
    (tmp / "kats-manifest.toml").write_text(manifest, encoding="utf-8")


def run_guard(tmp: pathlib.Path) -> tuple[int, str]:
    proc = subprocess.run(
        [sys.executable, str(GUARD), str(tmp)],
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout + proc.stderr


def rewrite_manifest_hash(tmp: pathlib.Path, new_hash: str) -> None:
    p = tmp / "kats-manifest.toml"
    lines = p.read_text(encoding="utf-8").splitlines()
    out = [f'sha256 = "{new_hash}"' if ln.startswith("sha256 = ") else ln for ln in lines]
    p.write_text("\n".join(out) + "\n", encoding="utf-8")


# --- mutations -------------------------------------------------------------
# Each returns the CHECK id it must provoke.


def mutate_uncovered_file(tmp: pathlib.Path) -> str:
    (tmp / "vectors" / "undeclared.rsp").write_text("# nope\n" + VECTOR_BODY, encoding="utf-8")
    return "CHECK 2"


def mutate_tampered_content(tmp: pathlib.Path) -> str:
    f = tmp / "vectors" / "fixture_regression_pin.rsp"
    f.write_text(f.read_text(encoding="utf-8") + "ss = DEADBEEF\n", encoding="utf-8")
    return "CHECK 3"


def mutate_banned_name(tmp: pathlib.Path) -> str:
    src = tmp / "vectors" / "fixture_regression_pin.rsp"
    dst = tmp / "vectors" / "official_fixture.rsp"
    shutil.move(str(src), str(dst))
    p = tmp / "kats-manifest.toml"
    p.write_text(
        p.read_text(encoding="utf-8").replace(
            "vectors/fixture_regression_pin.rsp", "vectors/official_fixture.rsp"
        ),
        encoding="utf-8",
    )
    return "CHECK 4"


def mutate_empty_root(tmp: pathlib.Path) -> str:
    # A root that discovers nothing must be a failure, not "nothing to do". This is the
    # vacuity case: it is how a guard silently stops looking after files move.
    (tmp / "vectors" / "fixture_regression_pin.rsp").unlink()
    return "CHECK 1"


def mutate_header_contradicts_manifest(tmp: pathlib.Path) -> str:
    # The file calls itself authoritative upstream data while the manifest says self-generated.
    # This is precisely the laundering the card was filed about.
    f = tmp / "vectors" / "fixture_regression_pin.rsp"
    content = "# authoritative upstream reference vectors, official NIST source\n" + VECTOR_BODY
    f.write_text(content, encoding="utf-8")
    rewrite_manifest_hash(tmp, sha256_of(content))
    return "CHECK 5"


MUTATIONS = [
    ("uncovered file has no manifest entry", mutate_uncovered_file),
    ("file content changed, manifest hash stale", mutate_tampered_content),
    ("self-generated file named 'official'", mutate_banned_name),
    ("scan root discovers zero files (vacuity)", mutate_empty_root),
    ("header contradicts manifest origin", mutate_header_contradicts_manifest),
]


def main() -> int:
    problems: list[str] = []

    # Baseline. Without this, every mutation result below is meaningless.
    with tempfile.TemporaryDirectory() as d:
        tmp = pathlib.Path(d)
        build_fixture(tmp)
        code, out = run_guard(tmp)
        if code != 0:
            problems.append(
                "BASELINE: the known-good fixture did NOT pass (exit "
                f"{code}). Every mutation case below would be vacuous, since a failure could "
                f"predate the mutation. Output:\n{out}"
            )
            print("\n".join(problems))
            return 1
        print("  ok   BASELINE: known-good fixture passes (exit 0)")

    for label, mutate in MUTATIONS:
        with tempfile.TemporaryDirectory() as d:
            tmp = pathlib.Path(d)
            build_fixture(tmp)
            expected_check = mutate(tmp)
            code, out = run_guard(tmp)

            if code == 0:
                problems.append(
                    f"{expected_check}: mutation {label!r} did NOT fail the guard. This check "
                    "cannot detect the defect it exists to detect."
                )
                continue
            if f"[{expected_check}]" not in out:
                problems.append(
                    f"{expected_check}: mutation {label!r} failed the guard, but not via "
                    f"{expected_check} -- so this case does not prove that check works. "
                    f"Output:\n{out}"
                )
                continue
            # The summary line for a failing check must not be labelled ok. An unconditional
            # "ok" against a check that just rejected the build misreads as a pass in CI logs.
            for line in out.splitlines():
                stripped = line.strip()
                if stripped.startswith("ok") and f"{expected_check}:" in stripped:
                    problems.append(
                        f"{expected_check}: the summary line is labelled 'ok' on a run where "
                        f"that check FAILED -- {stripped!r}"
                    )
            print(f"  ok   {expected_check} fails on: {label}")

    if problems:
        print("")
        print("selftest-kat-provenance-guard: FAILED")
        for p in problems:
            print(f"  - {p}")
        return 1

    print(f"selftest-kat-provenance-guard: OK ({len(MUTATIONS)} mutations + baseline)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
