name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Security and dependency scanning
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Install cargo-audit
        run: cargo install cargo-audit
      
      - name: Install cargo-outdated
        run: cargo install cargo-outdated
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Security audit
        run: cargo audit --deny warnings
      
      - name: Check for known vulnerabilities
        run: cargo audit --deny warnings --ignore RUSTSEC-2023-0001
      
      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1

  # Code quality and formatting
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Clippy linting
        run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Check for unused dependencies
        run: cargo check --all-targets --all-features

  # Unit and integration tests
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            features: "std"
          - target: x86_64-unknown-linux-gnu
            features: "std,all-algorithms"
          - target: x86_64-unknown-linux-gnu
            features: "std,wasm"
          - target: x86_64-unknown-linux-gnu
            features: "std,zkp"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Run tests
        run: cargo test --features "${{ matrix.features }}" --verbose
      
      - name: Run tests with release optimizations
        run: cargo test --features "${{ matrix.features }}" --release --verbose

  # WASM compilation and testing
  wasm:
    name: WASM Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            pkg
          key: ${{ runner.os }}-wasm-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-wasm-
      
      - name: Build WASM (web target)
        run: |
          echo "Building WASM for web target..."
          wasm-pack build --target web --features "wasm,all-algorithms" --verbose
          echo "WASM web build completed successfully"
      
      - name: Build WASM (nodejs target)
        run: |
          echo "Building WASM for nodejs target..."
          wasm-pack build --target nodejs --features "wasm,all-algorithms" --verbose
          echo "WASM nodejs build completed successfully"
      
      - name: Verify WASM artifacts
        run: |
          echo "Verifying WASM build artifacts..."
          ls -la pkg/ || echo "No pkg directory found"
          if [ -d "pkg" ]; then
            echo "WASM package contents:"
            ls -la pkg/
            echo "WASM file size:"
            ls -lh pkg/*.wasm 2>/dev/null || echo "No .wasm files found"
          fi

  # Performance benchmarks
  benchmark:
    name: Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Run benchmarks
        run: cargo bench --features "all-algorithms" --verbose

  # Documentation generation
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Generate documentation
        run: cargo doc --all-features --no-deps
      
      - name: Check documentation
        run: cargo doc --all-features --no-deps --document-private-items

  # Cross-platform compilation (Linux only)
  cross-compile-linux:
    name: Cross-Platform Build (Linux)
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build for target
        run: |
          echo "Building for target: ${{ matrix.target }}"
          cargo build --target ${{ matrix.target }} --features "all-algorithms" --release
          echo "Build completed successfully"
      
      - name: Check for target
        run: |
          echo "Checking for target: ${{ matrix.target }}"
          cargo check --target ${{ matrix.target }} --features "all-algorithms"
          echo "Check completed successfully"
      
      - name: Show build artifacts
        run: |
          echo "Build artifacts for target: ${{ matrix.target }}"
          ls -la target/${{ matrix.target }}/release/ || echo "No build artifacts found"

  # Windows compilation (separate job for proper toolchain)
  cross-compile-windows:
    name: Cross-Platform Build (Windows)
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build for target
        run: |
          echo "Building for target: ${{ matrix.target }}"
          cargo build --target ${{ matrix.target }} --features "all-algorithms" --release
          echo "Build completed successfully"
      
      - name: Check for target
        run: |
          echo "Checking for target: ${{ matrix.target }}"
          cargo check --target ${{ matrix.target }} --features "all-algorithms"
          echo "Check completed successfully"
      
      - name: Show build artifacts
        run: |
          echo "Build artifacts for target: ${{ matrix.target }}"
          dir target\${{ matrix.target }}\release\ || echo "No build artifacts found"

  # ARM64 compilation (separate job for proper toolchain)
  cross-compile-arm64:
    name: Cross-Platform Build (ARM64)
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      
      - name: Configure cross-compilation
        run: |
          mkdir -p ~/.cargo
          echo '[target.aarch64-unknown-linux-gnu]' >> ~/.cargo/config
          echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config
          echo 'ar = "aarch64-linux-gnu-ar"' >> ~/.cargo/config
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build for ARM64
        run: |
          echo "Building for target: aarch64-unknown-linux-gnu"
          cargo build --target aarch64-unknown-linux-gnu --features "all-algorithms" --release
          echo "Build completed successfully"
      
      - name: Check for ARM64
        run: |
          echo "Checking for target: aarch64-unknown-linux-gnu"
          cargo check --target aarch64-unknown-linux-gnu --features "all-algorithms"
          echo "Check completed successfully"
      
      - name: Show build artifacts
        run: |
          echo "Build artifacts for target: aarch64-unknown-linux-gnu"
          ls -la target/aarch64-unknown-linux-gnu/release/ || echo "No build artifacts found"

  # macOS compilation (separate job for proper toolchain)
  cross-compile-macos:
    name: Cross-Platform Build (macOS)
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build for target
        run: |
          echo "Building for target: ${{ matrix.target }}"
          cargo build --target ${{ matrix.target }} --features "all-algorithms" --release
          echo "Build completed successfully"
      
      - name: Check for target
        run: |
          echo "Checking for target: ${{ matrix.target }}"
          cargo check --target ${{ matrix.target }} --features "all-algorithms"
          echo "Check completed successfully"
      
      - name: Show build artifacts
        run: |
          echo "Build artifacts for target: ${{ matrix.target }}"
          ls -la target/${{ matrix.target }}/release/ || echo "No build artifacts found"

  # Constant-time verification (critical for crypto)
  constant-time:
    name: Constant-Time Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Install cargo-valgrind
        run: cargo install cargo-valgrind
      
      - name: Run constant-time tests
        run: cargo test --features "all-algorithms" --test constant_time
